services:
  db:
#    image: postgres:15
#    image: postgres:16.9-alpine3.22
    image: postgres:13-alpine
    container_name: barbershopp-db
#    restart: always
    environment:
      POSTGRES_DB: barbershop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
